test:
	sbt test

pctest:
	sbt "testOnly PCTester"
regfiletest:
	sbt "testOnly RegFileTester"

instructionmemtest:
	sbt "testOnly InstructionMemTester"

idtest:
	sbt "testOnly IDTester"


run:
	sbt run 

clean:
	rm -rf generate/*
	rm -rf test_run_dir/*